version: "3.9"
services:
  bot:
    image: gcr.io/${PROJECT_ID}/${IMAGE}:${GITHUB_SHA}
    container_name: discord-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "5000"
    environment:
      - DISCORD_TOKEN
      - STAGE=prod
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
  mongodb:
    image: mongo
    container_name: discord-bot-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /mongodb:/data/db
