version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: ./build/Dockerfile.bot
    container_name: discord-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - .:/bot
    ports:
      - "5000"
    environment:
      - DISCORD_TOKEN
      - STAGE=${STAGE:-dev}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
  mongodb:
    image: mongo
    container_name: discord-bot-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
