version: "3.9"
services:
  bot:
    build:
      context: .
      args:
        - POETRY_VERSION=1.1.7
      dockerfile: ./build/Dockerfile.bot
    container_name: discord-bot
    depends_on:
      - mongodb
    volumes:
      - .:/bot
    environment:
      - DISCORD_TOKEN
      - STAGE=${STAGE:-dev}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
  mongodb:
    image: mongo
    container_name: discord-bot-db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
