name: Cleanup Workflow

on:
  workflow_dispatch:
  schedule:
    # runs every Sunday at 00:00 UTC
    - cron: '0 0 * * SUN'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: discord-bot

jobs:
  prune-registry:
    name: Prune Container Registry
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event_name == 'schedule' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: |-
          echo Prune all before $(date +%F)
          ./.github/scripts/gcrgc.sh "gcr.io/$PROJECT_ID/$IMAGE" $(date +%F)
